name: "CI - Deploy to Azure Web App + smoke tests"

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/deploy-webapp.yml"
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-lab001
  PACKAGE_PATH: app

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "webapp-${{ github.ref_name }}"
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip artifact
        run: |
          rm -f app.zip
          cd "$PACKAGE_PATH"
          zip -r ../app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip

      - name: Warm-up
        run: sleep 15

      - name: Smoke test - /
        shell: bash
        run: |
          URL="https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
          echo "Testing $URL"
          for i in {1..30}; do
            CODE=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
            BODY=$(curl -s "$URL" || true)
            echo "HTTP $CODE: $(echo "$BODY" | head -c 200)"
            if [ "$CODE" -eq 200 ] && echo "$BODY" | grep -q "Hello Frontend!"; then
              echo "OK: Home responded"
              exit 0
            fi
            sleep 5
          done
          echo "Home did not respond in time"; exit 1

      - name: Smoke test - /backend
        shell: bash
        run: |
          URL="https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/backend"
          echo "Testing $URL"
          for i in {1..30}; do
            CODE=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
            BODY=$(curl -s "$URL" || true)
            echo "HTTP $CODE: $(echo "$BODY" | head -c 200)"
            if [ "$CODE" -eq 200 ] && echo "$BODY" | grep -q "Backend says:"; then
              echo "OK: Backend responded"
              exit 0
            fi
            sleep 5
          done
          echo "/backend did not respond in time"; exit 1
